
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 03 12:05:42 CDT 2023
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PorcentajeIGUAL = 11;
  public static final int AS = 66;
  public static final int IDENTIFIER = 81;
  public static final int FROM = 89;
  public static final int DIVISION = 26;
  public static final int TYPEOF = 44;
  public static final int TYPE = 88;
  public static final int IMPLEMENTS = 67;
  public static final int CONST = 52;
  public static final int EXPORT = 60;
  public static final int scanner = 6;
  public static final int GET = 78;
  public static final int CONSTRUCTOR = 77;
  public static final int ENUM = 59;
  public static final int CATCH = 50;
  public static final int REQUIRE = 10;
  public static final int THROW = 41;
  public static final int POR = 25;
  public static final int DECLARE = 92;
  public static final int YIELD = 75;
  public static final int PROTECTED = 72;
  public static final int INTEGER_LITERAL = 82;
  public static final int FALSE = 62;
  public static final int NOT = 21;
  public static final int ERROR = 93;
  public static final int MENORQUE = 16;
  public static final int VAR = 45;
  public static final int PACKAGE = 70;
  public static final int EQ = 23;
  public static final int CLASS = 51;
  public static final int INCREMENTO = 12;
  public static final int NUMBER = 84;
  public static final int SUPER = 38;
  public static final int ABSTRACT = 28;
  public static final int TRUE = 42;
  public static final int PLUS = 24;
  public static final int WHILE = 47;
  public static final int MODULE = 79;
  public static final int EXTENDS = 61;
  public static final int DELETE = 56;
  public static final int PORCENTAJE = 27;
  public static final int INTERFACE = 68;
  public static final int BOOLEAN = 29;
  public static final int SWITCH = 39;
  public static final int DO = 57;
  public static final int FOR = 64;
  public static final int PORIGUAL = 8;
  public static final int VOID = 46;
  public static final int DECREMENTO = 13;
  public static final int PUBLIC = 73;
  public static final int RETURN = 37;
  public static final int ELSE = 58;
  public static final int TRY = 43;
  public static final int BREAK = 30;
  public static final int INT = 2;
  public static final int REQUIERE = 80;
  public static final int WITCH = 48;
  public static final int STRING_LITERAL = 83;
  public static final int EQEQ = 22;
  public static final int NULL = 36;
  public static final int EOF = 0;
  public static final int THIS = 40;
  public static final int DEFAULT = 55;
  public static final int SUMA = 3;
  public static final int FUNCTION = 65;
  public static final int DIVISIONIGUAL = 9;
  public static final int IMPORT = 32;
  public static final int MENORIGUAL = 17;
  public static final int DEBUGGER = 54;
  public static final int IN = 33;
  public static final int COMILLA = 4;
  public static final int OR = 20;
  public static final int SET = 85;
  public static final int error = 1;
  public static final int FINALLY = 63;
  public static final int MASIGUAL = 5;
  public static final int CONTINUE = 53;
  public static final int IF = 31;
  public static final int INSTANCEOF = 34;
  public static final int MAYORQUE = 15;
  public static final int OF = 90;
  public static final int ANY = 76;
  public static final int MENOSIGUAL = 7;
  public static final int SYMBOL = 87;
  public static final int CASE = 49;
  public static final int MAYORIGUAL = 18;
  public static final int NEW = 35;
  public static final int STRING = 86;
  public static final int COMPARAIUAL = 14;
  public static final int AND = 19;
  public static final int PRIVATE = 71;
  public static final int STATIC = 74;
  public static final int WITH = 91;
  public static final int LET = 69;
}

