
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 02 21:12:14 CDT 2023
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 64;
  public static final int IDENTIFIER = 79;
  public static final int PORCENTAJEIGUAL = 9;
  public static final int FROM = 87;
  public static final int DIVISION = 24;
  public static final int TYPEOF = 42;
  public static final int TYPE = 86;
  public static final int IMPLEMENTS = 65;
  public static final int CONST = 50;
  public static final int EXPORT = 58;
  public static final int GET = 76;
  public static final int CONSTRUCTOR = 75;
  public static final int ENUM = 57;
  public static final int CATCH = 48;
  public static final int THROW = 39;
  public static final int POR = 23;
  public static final int DECLARE = 90;
  public static final int YIELD = 73;
  public static final int PROTECTED = 70;
  public static final int INTEGER_LITERAL = 80;
  public static final int FALSE = 60;
  public static final int NOT = 19;
  public static final int ERROR = 91;
  public static final int MENORQUE = 14;
  public static final int VAR = 43;
  public static final int PACKAGE = 68;
  public static final int EQ = 21;
  public static final int CLASS = 49;
  public static final int INCREMENTO = 10;
  public static final int NUMBER = 82;
  public static final int SUPER = 36;
  public static final int ABSTRACT = 26;
  public static final int TRUE = 40;
  public static final int PLUS = 22;
  public static final int WHILE = 45;
  public static final int MODULE = 77;
  public static final int EXTENDS = 59;
  public static final int DELETE = 54;
  public static final int PORCENTAJE = 25;
  public static final int INTERFACE = 66;
  public static final int BOOLEAN = 27;
  public static final int SWITCH = 37;
  public static final int DO = 55;
  public static final int FOR = 62;
  public static final int PORIGUAL = 7;
  public static final int VOID = 44;
  public static final int DECREMENTO = 11;
  public static final int PUBLIC = 71;
  public static final int RETURN = 35;
  public static final int ELSE = 56;
  public static final int TRY = 41;
  public static final int BREAK = 28;
  public static final int INT = 2;
  public static final int REQUIERE = 78;
  public static final int WITCH = 46;
  public static final int STRING_LITERAL = 81;
  public static final int EQEQ = 20;
  public static final int NULL = 34;
  public static final int EOF = 0;
  public static final int THIS = 38;
  public static final int DEFAULT = 53;
  public static final int SUMA = 3;
  public static final int DIVISIONIGUAL = 8;
  public static final int IMPORT = 30;
  public static final int MENORIGUAL = 15;
  public static final int DEBUGGER = 52;
  public static final int IN = 31;
  public static final int COMILLA = 4;
  public static final int OR = 18;
  public static final int SET = 83;
  public static final int error = 1;
  public static final int FINALLY = 61;
  public static final int MASIGUAL = 5;
  public static final int CONTINUE = 51;
  public static final int FUCTION = 63;
  public static final int IF = 29;
  public static final int INSTANCEOF = 32;
  public static final int MAYORQUE = 13;
  public static final int OF = 88;
  public static final int ANY = 74;
  public static final int MENOSIGUAL = 6;
  public static final int SYMBOL = 85;
  public static final int CASE = 47;
  public static final int MAYORIGUAL = 16;
  public static final int NEW = 33;
  public static final int STRING = 84;
  public static final int COMPARAIUAL = 12;
  public static final int AND = 17;
  public static final int PRIVATE = 69;
  public static final int STATIC = 72;
  public static final int WITH = 89;
  public static final int LET = 67;
}

