
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 13 16:07:38 CDT 2023
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PorcentajeIGUAL = 20;
  public static final int AS = 76;
  public static final int IDENTIFIER = 93;
  public static final int FROM = 101;
  public static final int DIVISION = 35;
  public static final int TYPEOF = 53;
  public static final int TYPE = 100;
  public static final int Menos = 80;
  public static final int IMPLEMENTS = 77;
  public static final int CONST = 61;
  public static final int punto = 9;
  public static final int puntoYcoma = 11;
  public static final int EXPORT = 69;
  public static final int scanner = 13;
  public static final int GET = 90;
  public static final int CONSTRUCTOR = 89;
  public static final int ENUM = 68;
  public static final int llave_open = 6;
  public static final int CATCH = 59;
  public static final int REQUIRE = 19;
  public static final int THROW = 50;
  public static final int POR = 34;
  public static final int DECLARE = 104;
  public static final int YIELD = 87;
  public static final int PROTECTED = 84;
  public static final int INTEGER_LITERAL = 94;
  public static final int FALSE = 71;
  public static final int NOT = 30;
  public static final int corchete_open = 4;
  public static final int ERROR = 105;
  public static final int MENORQUE = 25;
  public static final int VAR = 54;
  public static final int PACKAGE = 82;
  public static final int EQ = 32;
  public static final int CLASS = 60;
  public static final int INCREMENTO = 21;
  public static final int NUMBER = 96;
  public static final int SUPER = 47;
  public static final int ABSTRACT = 37;
  public static final int TRUE = 51;
  public static final int corchete_close = 5;
  public static final int PLUS = 33;
  public static final int WHILE = 56;
  public static final int MODULE = 91;
  public static final int EXTENDS = 70;
  public static final int DELETE = 65;
  public static final int PORCENTAJE = 36;
  public static final int INTERFACE = 78;
  public static final int BOOLEAN = 38;
  public static final int SWITCH = 48;
  public static final int FOR = 74;
  public static final int DO = 66;
  public static final int PORIGUAL = 17;
  public static final int VOID = 55;
  public static final int DECREMENTO = 22;
  public static final int PUBLIC = 85;
  public static final int RETURN = 46;
  public static final int ELSE = 67;
  public static final int TRY = 52;
  public static final int BREAK = 39;
  public static final int PARENTHESIS_CLOSE = 16;
  public static final int INT = 2;
  public static final int REQUIERE = 92;
  public static final int WITCH = 57;
  public static final int llave_close = 7;
  public static final int STRING_LITERAL = 95;
  public static final int EQEQ = 31;
  public static final int NULL = 45;
  public static final int EOF = 0;
  public static final int THIS = 49;
  public static final int DEFAULT = 64;
  public static final int SUMA = 8;
  public static final int FUNCTION = 75;
  public static final int DIVISIONIGUAL = 18;
  public static final int IMPORT = 41;
  public static final int MENORIGUAL = 26;
  public static final int DEBUGGER = 63;
  public static final int IN = 42;
  public static final int COMILLA = 10;
  public static final int OR = 29;
  public static final int SET = 97;
  public static final int error = 1;
  public static final int FINALLY = 73;
  public static final int MASIGUAL = 12;
  public static final int CONTINUE = 62;
  public static final int IF = 40;
  public static final int INSTANCEOF = 43;
  public static final int MAYORQUE = 24;
  public static final int OF = 102;
  public static final int ANY = 88;
  public static final int PARENTHESIS_OPEN = 15;
  public static final int MENOSIGUAL = 14;
  public static final int SYMBOL = 99;
  public static final int CASE = 58;
  public static final int MAYORIGUAL = 27;
  public static final int NEW = 44;
  public static final int coma = 81;
  public static final int STRING = 98;
  public static final int COMPARAIUAL = 23;
  public static final int AND = 28;
  public static final int PRIVATE = 83;
  public static final int STATIC = 86;
  public static final int Dospunto = 3;
  public static final int WITH = 103;
  public static final int LET = 79;
  public static final int Comment = 72;
}

