/* The following code was generated by JFlex 1.6.1 */

/* JFlex example: partial Java language lexer specification */
package compilador;
import java_cup.runtime.*;

/**
* This class is a simple example lexer.
*/

class TypeScriptLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\2\1\57\1\60\1\1\16\7\4\0\1\3\1\66"+
    "\1\55\1\0\1\6\1\65\1\71\1\0\1\43\1\44\1\5\1\62"+
    "\1\54\1\64\1\46\1\4\1\10\11\11\1\47\1\45\1\67\1\63"+
    "\1\70\2\0\16\6\1\31\3\6\1\56\7\6\1\50\1\73\1\51"+
    "\1\0\1\6\1\0\1\12\1\13\1\17\1\37\1\22\1\26\1\40"+
    "\1\34\1\25\1\6\1\24\1\21\1\27\1\23\1\20\1\30\1\42"+
    "\1\16\1\14\1\15\1\33\1\36\1\32\1\41\1\35\1\6\1\52"+
    "\1\72\1\53\1\0\6\7\1\61\32\7\2\0\4\6\4\0\1\6"+
    "\2\0\1\7\7\0\1\6\4\0\1\6\5\0\27\6\1\0\37\6"+
    "\1\0\u01ca\6\4\0\14\6\16\0\5\6\7\0\1\6\1\0\1\6"+
    "\21\0\160\7\5\6\1\0\2\6\2\0\4\6\10\0\1\6\1\0"+
    "\3\6\1\0\1\6\1\0\24\6\1\0\123\6\1\0\213\6\1\0"+
    "\5\7\2\0\236\6\11\0\46\6\2\0\1\6\7\0\47\6\7\0"+
    "\1\6\1\0\55\7\1\0\1\7\1\0\2\7\1\0\2\7\1\0"+
    "\1\7\10\0\33\6\5\0\3\6\15\0\5\7\6\0\1\6\4\0"+
    "\13\7\5\0\53\6\37\7\4\0\2\6\1\7\143\6\1\0\1\6"+
    "\10\7\1\0\6\7\2\6\2\7\1\0\4\7\2\6\12\7\3\6"+
    "\2\0\1\6\17\0\1\7\1\6\1\7\36\6\33\7\2\0\131\6"+
    "\13\7\1\6\16\0\12\7\41\6\11\7\2\6\4\0\1\6\5\0"+
    "\26\6\4\7\1\6\11\7\1\6\3\7\1\6\5\7\22\0\31\6"+
    "\3\7\104\0\1\6\1\0\13\6\67\0\33\7\1\0\4\7\66\6"+
    "\3\7\1\6\22\7\1\6\7\7\12\6\2\7\2\0\12\7\1\0"+
    "\7\6\1\0\7\6\1\0\3\7\1\0\10\6\2\0\2\6\2\0"+
    "\26\6\1\0\7\6\1\0\1\6\3\0\4\6\2\0\1\7\1\6"+
    "\7\7\2\0\2\7\2\0\3\7\1\6\10\0\1\7\4\0\2\6"+
    "\1\0\3\6\2\7\2\0\12\7\4\6\7\0\1\6\5\0\3\7"+
    "\1\0\6\6\4\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6"+
    "\1\0\2\6\1\0\2\6\2\0\1\7\1\0\5\7\4\0\2\7"+
    "\2\0\3\7\3\0\1\7\7\0\4\6\1\0\1\6\7\0\14\7"+
    "\3\6\1\7\13\0\3\7\1\0\11\6\1\0\3\6\1\0\26\6"+
    "\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7\1\6\10\7"+
    "\1\0\3\7\1\0\3\7\2\0\1\6\17\0\2\6\2\7\2\0"+
    "\12\7\1\0\1\6\17\0\3\7\1\0\10\6\2\0\2\6\2\0"+
    "\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7\1\6"+
    "\7\7\2\0\2\7\2\0\3\7\10\0\2\7\4\0\2\6\1\0"+
    "\3\6\2\7\2\0\12\7\1\0\1\6\20\0\1\7\1\6\1\0"+
    "\6\6\3\0\3\6\1\0\4\6\3\0\2\6\1\0\1\6\1\0"+
    "\2\6\3\0\2\6\3\0\3\6\3\0\14\6\4\0\5\7\3\0"+
    "\3\7\1\0\4\7\2\0\1\6\6\0\1\7\16\0\12\7\11\0"+
    "\1\6\7\0\3\7\1\0\10\6\1\0\3\6\1\0\27\6\1\0"+
    "\12\6\1\0\5\6\3\0\1\6\7\7\1\0\3\7\1\0\4\7"+
    "\7\0\2\7\1\0\2\6\6\0\2\6\2\7\2\0\12\7\22\0"+
    "\2\7\1\0\10\6\1\0\3\6\1\0\27\6\1\0\12\6\1\0"+
    "\5\6\2\0\1\7\1\6\7\7\1\0\3\7\1\0\4\7\7\0"+
    "\2\7\7\0\1\6\1\0\2\6\2\7\2\0\12\7\1\0\2\6"+
    "\17\0\2\7\1\0\10\6\1\0\3\6\1\0\51\6\2\0\1\6"+
    "\7\7\1\0\3\7\1\0\4\7\1\6\10\0\1\7\10\0\2\6"+
    "\2\7\2\0\12\7\12\0\6\6\2\0\2\7\1\0\22\6\3\0"+
    "\30\6\1\0\11\6\1\0\1\6\2\0\7\6\3\0\1\7\4\0"+
    "\6\7\1\0\1\7\1\0\10\7\22\0\2\7\15\0\60\6\1\7"+
    "\2\6\7\7\4\0\10\6\10\7\1\0\12\7\47\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\0\1\6\2\0\1\6\6\0\4\6\1\0"+
    "\7\6\1\0\3\6\1\0\1\6\1\0\1\6\2\0\2\6\1\0"+
    "\4\6\1\7\2\6\6\7\1\0\2\7\1\6\2\0\5\6\1\0"+
    "\1\6\1\0\6\7\2\0\12\7\2\0\4\6\40\0\1\6\27\0"+
    "\2\7\6\0\12\7\13\0\1\7\1\0\1\7\1\0\1\7\4\0"+
    "\2\7\10\6\1\0\44\6\4\0\24\7\1\0\2\7\5\6\13\7"+
    "\1\0\44\7\11\0\1\7\71\0\53\6\24\7\1\6\12\7\6\0"+
    "\6\6\4\7\4\6\3\7\1\6\3\7\2\6\7\7\3\6\4\7"+
    "\15\6\14\7\1\6\17\7\2\0\46\6\1\0\1\6\5\0\1\6"+
    "\2\0\53\6\1\0\u014d\6\1\0\4\6\2\0\7\6\1\0\1\6"+
    "\1\0\4\6\2\0\51\6\1\0\4\6\2\0\41\6\1\0\4\6"+
    "\2\0\7\6\1\0\1\6\1\0\4\6\2\0\17\6\1\0\71\6"+
    "\1\0\4\6\2\0\103\6\2\0\3\7\40\0\20\6\20\0\125\6"+
    "\14\0\u026c\6\2\0\21\6\1\0\32\6\5\0\113\6\3\0\3\6"+
    "\17\0\15\6\1\0\4\6\3\7\13\0\22\6\3\7\13\0\22\6"+
    "\2\7\14\0\15\6\1\0\3\6\1\0\2\7\14\0\64\6\40\7"+
    "\3\0\1\6\3\0\2\6\1\7\2\0\12\7\41\0\3\7\2\0"+
    "\12\7\6\0\130\6\10\0\51\6\1\7\1\6\5\0\106\6\12\0"+
    "\35\6\3\0\14\7\4\0\14\7\12\0\12\7\36\6\2\0\5\6"+
    "\13\0\54\6\4\0\21\7\7\6\2\7\6\0\12\7\46\0\27\6"+
    "\5\7\4\0\65\6\12\7\1\0\35\7\2\0\13\7\6\0\12\7"+
    "\15\0\1\6\130\0\5\7\57\6\21\7\7\6\4\0\12\7\21\0"+
    "\11\7\14\0\3\7\36\6\15\7\2\6\12\7\54\6\16\7\14\0"+
    "\44\6\24\7\10\0\12\7\3\0\3\6\12\7\44\6\122\0\3\7"+
    "\1\0\25\7\4\6\1\7\4\6\3\7\2\6\11\0\300\6\47\7"+
    "\25\0\4\7\u0116\6\2\0\6\6\2\0\46\6\2\0\6\6\2\0"+
    "\10\6\1\0\1\6\1\0\1\6\1\0\1\6\1\0\37\6\2\0"+
    "\65\6\1\0\7\6\1\0\1\6\3\0\3\6\1\0\7\6\3\0"+
    "\4\6\2\0\6\6\4\0\15\6\5\0\3\6\1\0\7\6\16\0"+
    "\5\7\30\0\1\57\1\57\5\7\20\0\2\6\23\0\1\6\13\0"+
    "\5\7\5\0\6\7\1\0\1\6\15\0\1\6\20\0\15\6\3\0"+
    "\33\6\25\0\15\7\4\0\1\7\3\0\14\7\21\0\1\6\4\0"+
    "\1\6\2\0\12\6\1\0\1\6\3\0\5\6\6\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\4\6\1\0\13\6\2\0\4\6\5\0"+
    "\5\6\4\0\1\6\21\0\51\6\u0a77\0\57\6\1\0\57\6\1\0"+
    "\205\6\6\0\4\6\3\7\2\6\14\0\46\6\1\0\1\6\5\0"+
    "\1\6\2\0\70\6\7\0\1\6\17\0\1\7\27\6\11\0\7\6"+
    "\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6"+
    "\1\0\7\6\1\0\7\6\1\0\40\7\57\0\1\6\u01d5\0\3\6"+
    "\31\0\11\6\6\7\1\0\5\6\2\0\5\6\4\0\126\6\2\0"+
    "\2\7\2\0\3\6\1\0\132\6\1\0\4\6\5\0\51\6\3\0"+
    "\136\6\21\0\33\6\65\0\20\6\u0200\0\u19b6\6\112\0\u51cd\6\63\0"+
    "\u048d\6\103\0\56\6\2\0\u010d\6\3\0\20\6\12\7\2\6\24\0"+
    "\57\6\1\7\4\0\12\7\1\0\31\6\7\0\1\7\120\6\2\7"+
    "\45\0\11\6\2\0\147\6\2\0\4\6\1\0\4\6\14\0\13\6"+
    "\115\0\12\6\1\7\3\6\1\7\4\6\1\7\27\6\5\7\20\0"+
    "\1\6\7\0\64\6\14\0\2\7\62\6\21\7\13\0\12\7\6\0"+
    "\22\7\6\6\3\0\1\6\4\0\12\7\34\6\10\7\2\0\27\6"+
    "\15\7\14\0\35\6\3\0\4\7\57\6\16\7\16\0\1\6\12\7"+
    "\46\0\51\6\16\7\11\0\3\6\1\7\10\6\2\7\2\0\12\7"+
    "\6\0\27\6\3\0\1\6\1\7\4\0\60\6\1\7\1\6\3\7"+
    "\2\6\2\7\5\6\2\7\1\6\1\7\1\6\30\0\3\6\2\0"+
    "\13\6\5\7\2\0\3\6\2\7\12\0\6\6\2\0\6\6\2\0"+
    "\6\6\11\0\7\6\1\0\7\6\221\0\43\6\10\7\1\0\2\7"+
    "\2\0\12\7\6\0\u2ba4\6\14\0\27\6\4\0\61\6\u2104\0\u016e\6"+
    "\2\0\152\6\46\0\7\6\14\0\5\6\5\0\1\6\1\7\12\6"+
    "\1\0\15\6\1\0\5\6\1\0\1\6\1\0\2\6\1\0\2\6"+
    "\1\0\154\6\41\0\u016b\6\22\0\100\6\2\0\66\6\50\0\15\6"+
    "\3\0\20\7\20\0\7\7\14\0\2\6\30\0\3\6\31\0\1\6"+
    "\6\0\5\6\1\0\207\6\2\0\1\7\4\0\1\6\13\0\12\7"+
    "\7\0\32\6\4\0\1\6\1\0\32\6\13\0\131\6\3\0\6\6"+
    "\2\0\6\6\2\0\6\6\2\0\3\6\3\0\2\6\3\0\2\6"+
    "\22\0\3\7\4\0\14\6\1\0\32\6\1\0\23\6\1\0\2\6"+
    "\1\0\17\6\2\0\16\6\42\0\173\6\105\0\65\6\210\0\1\7"+
    "\202\0\35\6\3\0\61\6\57\0\37\6\21\0\33\6\65\0\36\6"+
    "\2\0\44\6\4\0\10\6\1\0\5\6\52\0\236\6\2\0\12\7"+
    "\u0356\0\6\6\2\0\1\6\1\0\54\6\1\0\2\6\3\0\1\6"+
    "\2\0\27\6\252\0\26\6\12\0\32\6\106\0\70\6\6\0\2\6"+
    "\100\0\1\6\3\7\1\0\2\7\5\0\4\7\4\6\1\0\3\6"+
    "\1\0\33\6\4\0\3\7\4\0\1\7\40\0\35\6\203\0\66\6"+
    "\12\0\26\6\12\0\23\6\215\0\111\6\u03b7\0\3\7\65\6\17\7"+
    "\37\0\12\7\20\0\3\7\55\6\13\7\2\0\1\7\22\0\31\6"+
    "\7\0\12\7\6\0\3\7\44\6\16\7\1\0\12\7\100\0\3\7"+
    "\60\6\16\7\4\6\13\0\12\7\u04a6\0\53\6\15\7\10\0\12\7"+
    "\u0936\0\u036f\6\221\0\143\6\u0b9d\0\u042f\6\u33d1\0\u0239\6\u04c7\0\105\6"+
    "\13\0\1\6\56\7\20\0\4\7\15\6\u4060\0\2\6\u2163\0\5\7"+
    "\3\0\26\7\2\0\7\7\36\0\4\7\224\0\3\7\u01bb\0\125\6"+
    "\1\0\107\6\1\0\2\6\2\0\1\6\2\0\2\6\2\0\4\6"+
    "\1\0\14\6\1\0\1\6\1\0\7\6\1\0\101\6\1\0\4\6"+
    "\2\0\10\6\1\0\7\6\1\0\34\6\1\0\4\6\1\0\5\6"+
    "\1\0\1\6\3\0\7\6\1\0\u0154\6\2\0\31\6\1\0\31\6"+
    "\1\0\37\6\1\0\31\6\1\0\37\6\1\0\31\6\1\0\37\6"+
    "\1\0\31\6\1\0\37\6\1\0\31\6\1\0\10\6\2\0\62\7"+
    "\u1600\0\4\6\1\0\33\6\1\0\2\6\1\0\1\6\2\0\1\6"+
    "\1\0\12\6\1\0\4\6\1\0\1\6\1\0\1\6\6\0\1\6"+
    "\4\0\1\6\1\0\1\6\1\0\1\6\1\0\3\6\1\0\2\6"+
    "\1\0\1\6\2\0\1\6\1\0\1\6\1\0\1\6\1\0\1\6"+
    "\1\0\1\6\1\0\2\6\1\0\1\6\2\0\4\6\1\0\7\6"+
    "\1\0\4\6\1\0\4\6\1\0\1\6\1\0\12\6\1\0\21\6"+
    "\5\0\3\6\1\0\5\6\1\0\21\6\u1144\0\ua6d7\6\51\0\u1035\6"+
    "\13\0\336\6\u3fe2\0\u021e\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\7\36\0\140\7\200\0\360\7\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\4\2\5\23\4\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\4\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\2\0\1\30\1\31\1\32\1\33\1\0"+
    "\1\34\1\35\1\4\1\36\17\4\1\37\6\4\1\40"+
    "\1\41\17\4\1\42\3\4\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\2\33\2\0\1\4\1\61\4\4\1\62"+
    "\4\4\1\63\11\4\1\64\4\4\1\65\7\4\1\66"+
    "\12\4\1\67\5\4\1\70\1\4\1\0\1\33\10\4"+
    "\1\71\1\4\1\72\1\73\2\4\1\74\4\4\1\75"+
    "\1\76\2\4\1\77\6\4\1\100\7\4\1\101\2\4"+
    "\1\102\6\4\1\103\4\4\1\104\1\4\1\105\3\4"+
    "\1\106\1\107\1\4\1\110\7\4\1\111\7\4\1\112"+
    "\1\113\7\4\1\114\1\115\1\116\1\117\1\120\1\121"+
    "\4\4\1\122\1\123\2\4\1\124\3\4\1\125\3\4"+
    "\1\126\2\4\1\127\3\4\1\130\1\131\2\4\1\132"+
    "\3\4\1\133\1\4\1\134\1\4\1\135\1\4\1\136"+
    "\1\137\1\0\1\4\1\140\1\4\1\141\3\4\1\142"+
    "\1\4\1\143\1\0\3\4\1\144\1\4\1\145\1\0"+
    "\2\4\1\146\1\147\1\0\1\4\1\150\1\0\1\4"+
    "\1\0\1\4\1\0\1\4\1\0\1\4\1\0\1\4"+
    "\1\0\1\4\1\0\1\4\1\0\1\4\1\0\1\151";

  private static int [] zzUnpackAction() {
    int [] result = new int[350];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\264\0\360\0\u012c\0\u0168\0\264"+
    "\0\u01a4\0\u01e0\0\u021c\0\u0258\0\u0294\0\u02d0\0\u030c\0\u0348"+
    "\0\u0384\0\u03c0\0\u03fc\0\u0438\0\u0474\0\u04b0\0\u04ec\0\u0528"+
    "\0\u0564\0\u05a0\0\u05dc\0\u0618\0\264\0\264\0\264\0\264"+
    "\0\264\0\264\0\264\0\264\0\264\0\264\0\264\0\u0654"+
    "\0\u0690\0\u06cc\0\u0708\0\u0744\0\u0780\0\u07bc\0\u07f8\0\u0834"+
    "\0\u0870\0\u08ac\0\264\0\u08e8\0\u0924\0\u0960\0\264\0\264"+
    "\0\u099c\0\u0168\0\u09d8\0\u0a14\0\u0a50\0\u0a8c\0\u0ac8\0\u0b04"+
    "\0\u0b40\0\u0b7c\0\u0bb8\0\u0bf4\0\u0c30\0\u0c6c\0\u0ca8\0\u0ce4"+
    "\0\u0d20\0\u0168\0\u0d5c\0\u0d98\0\u0dd4\0\u0e10\0\u0e4c\0\u0e88"+
    "\0\u0ec4\0\u0168\0\u0f00\0\u0f3c\0\u0f78\0\u0fb4\0\u0ff0\0\u102c"+
    "\0\u1068\0\u10a4\0\u10e0\0\u111c\0\u1158\0\u1194\0\u11d0\0\u120c"+
    "\0\u1248\0\u0168\0\u1284\0\u12c0\0\u12fc\0\264\0\264\0\264"+
    "\0\264\0\264\0\264\0\264\0\264\0\264\0\264\0\264"+
    "\0\264\0\264\0\264\0\u1338\0\264\0\u1374\0\u13b0\0\u13ec"+
    "\0\u0168\0\u1428\0\u1464\0\u14a0\0\u14dc\0\u0168\0\u1518\0\u1554"+
    "\0\u1590\0\u15cc\0\u0168\0\u1608\0\u1644\0\u1680\0\u16bc\0\u16f8"+
    "\0\u1734\0\u1770\0\u17ac\0\u17e8\0\u0168\0\u1824\0\u1860\0\u189c"+
    "\0\u18d8\0\u0168\0\u1914\0\u1950\0\u198c\0\u19c8\0\u1a04\0\u1a40"+
    "\0\u1a7c\0\u0168\0\u1ab8\0\u1af4\0\u1b30\0\u1b6c\0\u1ba8\0\u1be4"+
    "\0\u1c20\0\u1c5c\0\u1c98\0\u1cd4\0\u0168\0\u1d10\0\u1d4c\0\u1d88"+
    "\0\u1dc4\0\u1e00\0\u0168\0\u1e3c\0\u1e78\0\u1374\0\u1eb4\0\u1ef0"+
    "\0\u1f2c\0\u1f68\0\u1fa4\0\u1fe0\0\u201c\0\u2058\0\u0168\0\u2094"+
    "\0\u0168\0\u20d0\0\u210c\0\u2148\0\u0168\0\u2184\0\u21c0\0\u21fc"+
    "\0\u2238\0\u0168\0\u0168\0\u2274\0\u22b0\0\u0168\0\u22ec\0\u2328"+
    "\0\u2364\0\u23a0\0\u23dc\0\u2418\0\u0168\0\u2454\0\u2490\0\u24cc"+
    "\0\u2508\0\u2544\0\u2580\0\u25bc\0\u0168\0\u25f8\0\u2634\0\u0168"+
    "\0\u2670\0\u26ac\0\u26e8\0\u2724\0\u2760\0\u279c\0\u0168\0\u27d8"+
    "\0\u2814\0\u2850\0\u288c\0\u0168\0\u28c8\0\u0168\0\u2904\0\u2940"+
    "\0\u297c\0\u0168\0\u29b8\0\u29f4\0\u0168\0\u2a30\0\u2a6c\0\u2aa8"+
    "\0\u2ae4\0\u2b20\0\u2b5c\0\u2b98\0\u0168\0\u2bd4\0\u2c10\0\u2c4c"+
    "\0\u2c88\0\u2cc4\0\u2d00\0\u2d3c\0\u0168\0\u0168\0\u2d78\0\u2db4"+
    "\0\u2df0\0\u2e2c\0\u2e68\0\u2ea4\0\u2ee0\0\u0168\0\u0168\0\u0168"+
    "\0\u0168\0\u0168\0\u0168\0\u2f1c\0\u2f58\0\u2f94\0\u2fd0\0\u0168"+
    "\0\u0168\0\u300c\0\u3048\0\u0168\0\u3084\0\u30c0\0\u30fc\0\u0168"+
    "\0\u3138\0\u3174\0\u31b0\0\u0168\0\u31ec\0\u3228\0\u0168\0\u3264"+
    "\0\u32a0\0\u32dc\0\u0168\0\u0168\0\u3318\0\u3354\0\u0168\0\u3390"+
    "\0\u33cc\0\u3408\0\u0168\0\u3444\0\u0168\0\u3480\0\u0168\0\u34bc"+
    "\0\u0168\0\u0168\0\u34f8\0\u3534\0\u0168\0\u3570\0\u0168\0\u35ac"+
    "\0\u35e8\0\u3624\0\u0168\0\u3660\0\u0168\0\u369c\0\u36d8\0\u3714"+
    "\0\u3750\0\u0168\0\u378c\0\u0168\0\u37c8\0\u3804\0\u3840\0\u0168"+
    "\0\u0168\0\u387c\0\u38b8\0\u0168\0\u38f4\0\u3930\0\u396c\0\u39a8"+
    "\0\u39e4\0\u3a20\0\u3a5c\0\u3a98\0\u3ad4\0\u3b10\0\u3b4c\0\u3b88"+
    "\0\u3bc4\0\u3c00\0\u3c3c\0\u3c78\0\u3cb4\0\264";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[350];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\3\2\4\1\5\1\6\1\7\1\0\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\7\1\24\1\25\1\26\1\27"+
    "\1\7\1\30\2\7\1\31\1\32\1\33\1\34\2\7"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\0\1\4\1\0\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\1\60\1\61"+
    "\1\0\1\62\2\0\52\62\1\63\15\62\1\64\2\0"+
    "\1\4\171\0\1\65\1\66\55\0\1\67\73\0\1\70"+
    "\16\0\35\7\13\0\1\7\2\0\1\7\22\0\2\11"+
    "\70\0\5\7\1\71\1\72\6\7\1\73\17\7\13\0"+
    "\1\7\2\0\1\7\20\0\10\7\1\74\1\7\1\75"+
    "\22\7\13\0\1\7\2\0\1\7\20\0\7\7\1\76"+
    "\4\7\1\77\7\7\1\100\1\101\1\7\1\102\5\7"+
    "\13\0\1\7\2\0\1\7\20\0\10\7\1\103\15\7"+
    "\1\104\1\105\5\7\13\0\1\7\2\0\1\7\20\0"+
    "\14\7\1\106\20\7\13\0\1\7\2\0\1\7\20\0"+
    "\4\7\1\107\5\7\1\110\1\111\21\7\13\0\1\7"+
    "\2\0\1\7\20\0\20\7\1\112\14\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\113\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\13\7\1\114\1\7\1\115\15\7"+
    "\1\116\1\7\13\0\1\7\2\0\1\7\20\0\14\7"+
    "\1\117\10\7\1\120\7\7\13\0\1\7\2\0\1\7"+
    "\20\0\15\7\1\121\2\7\1\122\1\123\13\7\13\0"+
    "\1\7\2\0\1\7\20\0\4\7\1\124\3\7\1\125"+
    "\1\7\1\126\4\7\1\127\5\7\1\130\7\7\13\0"+
    "\1\7\2\0\1\7\20\0\12\7\1\131\22\7\13\0"+
    "\1\7\2\0\1\7\20\0\4\7\1\132\3\7\1\133"+
    "\14\7\1\134\7\7\13\0\1\7\2\0\1\7\20\0"+
    "\17\7\1\135\6\7\1\136\6\7\13\0\1\7\2\0"+
    "\1\7\20\0\17\7\1\137\15\7\13\0\1\7\2\0"+
    "\1\7\20\0\4\7\1\140\5\7\1\141\22\7\13\0"+
    "\1\7\2\0\1\7\20\0\12\7\1\142\1\7\1\143"+
    "\20\7\13\0\1\7\2\0\1\7\20\0\14\7\1\144"+
    "\20\7\13\0\1\7\2\0\1\7\20\0\27\7\1\145"+
    "\5\7\13\0\1\7\2\0\1\7\74\0\1\146\74\0"+
    "\1\147\73\0\1\150\1\151\72\0\1\152\73\0\1\153"+
    "\73\0\1\154\73\0\1\155\101\0\1\156\74\0\1\157"+
    "\1\0\1\62\2\0\52\62\1\0\15\62\16\0\1\160"+
    "\1\161\4\0\1\162\31\0\1\163\16\0\1\65\1\164"+
    "\1\165\71\65\5\166\1\167\66\166\6\0\6\7\1\170"+
    "\26\7\13\0\1\7\2\0\1\7\20\0\27\7\1\171"+
    "\5\7\13\0\1\7\2\0\1\7\20\0\14\7\1\172"+
    "\20\7\13\0\1\7\2\0\1\7\20\0\12\7\1\173"+
    "\22\7\13\0\1\7\2\0\1\7\20\0\4\7\1\174"+
    "\3\7\1\175\24\7\13\0\1\7\2\0\1\7\20\0"+
    "\7\7\1\176\25\7\13\0\1\7\2\0\1\7\20\0"+
    "\17\7\1\177\15\7\13\0\1\7\2\0\1\7\20\0"+
    "\22\7\1\200\12\7\13\0\1\7\2\0\1\7\20\0"+
    "\21\7\1\201\13\7\13\0\1\7\2\0\1\7\20\0"+
    "\25\7\1\202\1\7\1\203\5\7\13\0\1\7\2\0"+
    "\1\7\20\0\10\7\1\204\6\7\1\205\15\7\13\0"+
    "\1\7\2\0\1\7\20\0\22\7\1\206\12\7\13\0"+
    "\1\7\2\0\1\7\20\0\7\7\1\207\24\7\1\210"+
    "\13\0\1\7\2\0\1\7\20\0\6\7\1\211\1\212"+
    "\25\7\13\0\1\7\2\0\1\7\20\0\15\7\1\213"+
    "\17\7\13\0\1\7\2\0\1\7\20\0\4\7\1\214"+
    "\30\7\13\0\1\7\2\0\1\7\20\0\7\7\1\215"+
    "\25\7\13\0\1\7\2\0\1\7\20\0\6\7\1\216"+
    "\26\7\13\0\1\7\2\0\1\7\20\0\25\7\1\217"+
    "\7\7\13\0\1\7\2\0\1\7\20\0\7\7\1\220"+
    "\12\7\1\221\12\7\13\0\1\7\2\0\1\7\20\0"+
    "\24\7\1\222\10\7\13\0\1\7\2\0\1\7\20\0"+
    "\13\7\1\223\5\7\1\224\13\7\13\0\1\7\2\0"+
    "\1\7\20\0\6\7\1\225\1\226\25\7\13\0\1\7"+
    "\2\0\1\7\20\0\22\7\1\227\12\7\13\0\1\7"+
    "\2\0\1\7\20\0\13\7\1\230\21\7\13\0\1\7"+
    "\2\0\1\7\20\0\12\7\1\231\22\7\13\0\1\7"+
    "\2\0\1\7\20\0\10\7\1\232\24\7\13\0\1\7"+
    "\2\0\1\7\20\0\15\7\1\233\17\7\13\0\1\7"+
    "\2\0\1\7\20\0\15\7\1\234\17\7\13\0\1\7"+
    "\2\0\1\7\20\0\31\7\1\235\3\7\13\0\1\7"+
    "\2\0\1\7\20\0\11\7\1\236\23\7\13\0\1\7"+
    "\2\0\1\7\20\0\12\7\1\237\4\7\1\240\15\7"+
    "\13\0\1\7\2\0\1\7\20\0\5\7\1\241\27\7"+
    "\13\0\1\7\2\0\1\7\20\0\7\7\1\242\25\7"+
    "\13\0\1\7\2\0\1\7\20\0\17\7\1\243\15\7"+
    "\13\0\1\7\2\0\1\7\20\0\14\7\1\244\20\7"+
    "\13\0\1\7\2\0\1\7\20\0\10\7\1\245\24\7"+
    "\13\0\1\7\2\0\1\7\20\0\17\7\1\246\15\7"+
    "\13\0\1\7\2\0\1\7\20\0\5\7\1\247\3\7"+
    "\1\250\1\7\1\251\4\7\1\252\14\7\13\0\1\7"+
    "\2\0\1\7\20\0\7\7\1\253\25\7\13\0\1\7"+
    "\2\0\1\7\20\0\6\7\1\254\26\7\13\0\1\7"+
    "\2\0\1\7\14\0\1\165\71\0\5\166\1\255\72\166"+
    "\1\256\1\255\66\166\6\0\7\7\1\257\25\7\13\0"+
    "\1\7\2\0\1\7\20\0\4\7\1\260\30\7\13\0"+
    "\1\7\2\0\1\7\20\0\13\7\1\261\21\7\13\0"+
    "\1\7\2\0\1\7\20\0\7\7\1\262\25\7\13\0"+
    "\1\7\2\0\1\7\20\0\17\7\1\263\15\7\13\0"+
    "\1\7\2\0\1\7\20\0\7\7\1\264\25\7\13\0"+
    "\1\7\2\0\1\7\20\0\14\7\1\265\20\7\13\0"+
    "\1\7\2\0\1\7\20\0\5\7\1\266\27\7\13\0"+
    "\1\7\2\0\1\7\20\0\14\7\1\267\20\7\13\0"+
    "\1\7\2\0\1\7\20\0\12\7\1\270\22\7\13\0"+
    "\1\7\2\0\1\7\20\0\6\7\1\271\26\7\13\0"+
    "\1\7\2\0\1\7\20\0\14\7\1\272\20\7\13\0"+
    "\1\7\2\0\1\7\20\0\25\7\1\273\7\7\13\0"+
    "\1\7\2\0\1\7\20\0\25\7\1\274\7\7\13\0"+
    "\1\7\2\0\1\7\20\0\14\7\1\275\20\7\13\0"+
    "\1\7\2\0\1\7\20\0\11\7\1\276\23\7\13\0"+
    "\1\7\2\0\1\7\20\0\6\7\1\277\1\300\25\7"+
    "\13\0\1\7\2\0\1\7\20\0\6\7\1\301\26\7"+
    "\13\0\1\7\2\0\1\7\20\0\14\7\1\302\20\7"+
    "\13\0\1\7\2\0\1\7\20\0\21\7\1\303\13\7"+
    "\13\0\1\7\2\0\1\7\20\0\14\7\1\304\20\7"+
    "\13\0\1\7\2\0\1\7\20\0\12\7\1\305\22\7"+
    "\13\0\1\7\2\0\1\7\20\0\13\7\1\306\21\7"+
    "\13\0\1\7\2\0\1\7\20\0\5\7\1\307\27\7"+
    "\13\0\1\7\2\0\1\7\20\0\7\7\1\310\25\7"+
    "\13\0\1\7\2\0\1\7\20\0\14\7\1\311\20\7"+
    "\13\0\1\7\2\0\1\7\20\0\12\7\1\312\1\313"+
    "\21\7\13\0\1\7\2\0\1\7\20\0\6\7\1\314"+
    "\26\7\13\0\1\7\2\0\1\7\20\0\21\7\1\315"+
    "\13\7\13\0\1\7\2\0\1\7\20\0\4\7\1\316"+
    "\30\7\13\0\1\7\2\0\1\7\20\0\11\7\1\317"+
    "\23\7\13\0\1\7\2\0\1\7\20\0\25\7\1\320"+
    "\7\7\13\0\1\7\2\0\1\7\20\0\16\7\1\321"+
    "\16\7\13\0\1\7\2\0\1\7\20\0\7\7\1\322"+
    "\25\7\13\0\1\7\2\0\1\7\20\0\30\7\1\323"+
    "\4\7\13\0\1\7\2\0\1\7\20\0\13\7\1\324"+
    "\21\7\13\0\1\7\2\0\1\7\20\0\26\7\1\325"+
    "\6\7\13\0\1\7\2\0\1\7\20\0\13\7\1\326"+
    "\21\7\13\0\1\7\2\0\1\7\20\0\13\7\1\327"+
    "\21\7\13\0\1\7\2\0\1\7\20\0\31\7\1\330"+
    "\3\7\13\0\1\7\2\0\1\7\20\0\25\7\1\331"+
    "\7\7\13\0\1\7\2\0\1\7\20\0\13\7\1\332"+
    "\21\7\13\0\1\7\2\0\1\7\20\0\14\7\1\333"+
    "\20\7\13\0\1\7\2\0\1\7\20\0\4\7\1\334"+
    "\30\7\13\0\1\7\2\0\1\7\20\0\7\7\1\335"+
    "\25\7\13\0\1\7\2\0\1\7\12\0\4\166\1\165"+
    "\1\255\66\166\6\0\10\7\1\336\24\7\13\0\1\7"+
    "\2\0\1\7\20\0\16\7\1\337\16\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\340\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\17\7\1\341\15\7\13\0\1\7"+
    "\2\0\1\7\20\0\15\7\1\342\17\7\13\0\1\7"+
    "\2\0\1\7\20\0\11\7\1\343\23\7\13\0\1\7"+
    "\2\0\1\7\20\0\10\7\1\344\24\7\13\0\1\7"+
    "\2\0\1\7\20\0\12\7\1\345\22\7\13\0\1\7"+
    "\2\0\1\7\20\0\24\7\1\346\10\7\13\0\1\7"+
    "\2\0\1\7\20\0\23\7\1\347\11\7\13\0\1\7"+
    "\2\0\1\7\20\0\10\7\1\350\24\7\13\0\1\7"+
    "\2\0\1\7\20\0\17\7\1\351\15\7\13\0\1\7"+
    "\2\0\1\7\20\0\26\7\1\352\6\7\13\0\1\7"+
    "\2\0\1\7\20\0\7\7\1\353\25\7\13\0\1\7"+
    "\2\0\1\7\20\0\17\7\1\354\15\7\13\0\1\7"+
    "\2\0\1\7\20\0\6\7\1\355\26\7\13\0\1\7"+
    "\2\0\1\7\20\0\15\7\1\356\17\7\13\0\1\7"+
    "\2\0\1\7\20\0\10\7\1\357\24\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\360\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\4\7\1\361\30\7\13\0\1\7"+
    "\2\0\1\7\20\0\10\7\1\362\24\7\13\0\1\7"+
    "\2\0\1\7\20\0\10\7\1\363\24\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\364\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\365\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\13\7\1\366\21\7\13\0\1\7"+
    "\2\0\1\7\20\0\7\7\1\367\25\7\13\0\1\7"+
    "\2\0\1\7\20\0\13\7\1\370\21\7\13\0\1\7"+
    "\2\0\1\7\20\0\4\7\1\371\30\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\372\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\4\7\1\373\30\7\13\0\1\7"+
    "\2\0\1\7\20\0\17\7\1\374\15\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\375\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\31\7\1\376\3\7\13\0\1\7"+
    "\2\0\1\7\20\0\32\7\1\377\2\7\13\0\1\7"+
    "\2\0\1\7\20\0\4\7\1\u0100\30\7\13\0\1\7"+
    "\2\0\1\7\20\0\7\7\1\u0101\25\7\13\0\1\7"+
    "\2\0\1\7\20\0\25\7\1\u0102\7\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\u0103\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\4\7\1\u0104\30\7\13\0\1\7"+
    "\2\0\1\7\20\0\4\7\1\u0105\30\7\13\0\1\7"+
    "\2\0\1\7\20\0\11\7\1\u0106\23\7\13\0\1\7"+
    "\2\0\1\7\20\0\32\7\1\u0107\2\7\13\0\1\7"+
    "\2\0\1\7\20\0\26\7\1\u0108\6\7\13\0\1\7"+
    "\2\0\1\7\20\0\13\7\1\u0109\21\7\13\0\1\7"+
    "\2\0\1\7\20\0\20\7\1\u010a\14\7\13\0\1\7"+
    "\2\0\1\7\20\0\15\7\1\u010b\17\7\13\0\1\7"+
    "\2\0\1\7\20\0\10\7\1\u010c\24\7\13\0\1\7"+
    "\2\0\1\7\20\0\10\7\1\u010d\24\7\13\0\1\7"+
    "\2\0\1\7\20\0\15\7\1\u010e\17\7\13\0\1\7"+
    "\2\0\1\7\20\0\31\7\1\u010f\3\7\13\0\1\7"+
    "\2\0\1\7\20\0\7\7\1\u0110\25\7\13\0\1\7"+
    "\2\0\1\7\20\0\10\7\1\u0111\24\7\13\0\1\7"+
    "\2\0\1\7\20\0\15\7\1\u0112\17\7\13\0\1\7"+
    "\2\0\1\7\20\0\20\7\1\u0113\14\7\13\0\1\7"+
    "\2\0\1\7\20\0\7\7\1\u0114\25\7\13\0\1\7"+
    "\2\0\1\7\20\0\21\7\1\u0115\13\7\13\0\1\7"+
    "\2\0\1\7\20\0\13\7\1\u0116\21\7\13\0\1\7"+
    "\2\0\1\7\20\0\17\7\1\u0117\15\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\u0118\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\32\7\1\u0119\2\7\13\0\1\7"+
    "\2\0\1\7\20\0\11\7\1\u011a\23\7\13\0\1\7"+
    "\2\0\1\7\20\0\7\7\1\u011b\25\7\13\0\1\7"+
    "\2\0\1\7\20\0\11\7\1\u011c\23\7\13\0\1\7"+
    "\2\0\1\7\20\0\32\7\1\u011d\2\7\13\0\1\7"+
    "\2\0\1\7\20\0\10\7\1\u011e\24\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\u011f\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\13\7\1\u0120\21\7\13\0\1\7"+
    "\2\0\1\7\20\0\21\7\1\u0121\13\7\13\0\1\7"+
    "\2\0\1\7\20\0\11\7\1\u0122\23\7\13\0\1\7"+
    "\2\0\1\7\20\0\15\7\1\u0123\17\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\u0124\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\25\7\1\u0125\7\7\13\0\1\7"+
    "\2\0\1\7\20\0\25\7\1\u0126\7\7\13\0\1\7"+
    "\2\0\1\7\20\0\6\7\1\u0127\26\7\13\0\1\7"+
    "\2\0\1\7\20\0\11\7\1\u0128\23\7\13\0\1\7"+
    "\2\0\1\7\20\0\4\7\1\u0129\30\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\u012a\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\27\7\1\u012b\5\7\13\0\1\7"+
    "\2\0\1\7\20\0\12\7\1\u012c\22\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\u012d\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\7\7\1\u012e\25\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\u012f\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\u0130\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\14\7\1\u0131\20\7\13\0\1\7"+
    "\2\0\1\7\20\0\7\7\1\u0132\25\7\13\0\1\7"+
    "\2\0\1\7\12\0\1\u0133\2\0\3\u0133\35\u0134\13\u0133"+
    "\1\u0134\2\0\1\7\12\u0133\6\0\7\7\1\u0135\25\7"+
    "\13\0\1\7\2\0\1\7\20\0\11\7\1\u0136\23\7"+
    "\13\0\1\7\2\0\1\7\20\0\14\7\1\u0137\20\7"+
    "\13\0\1\7\2\0\1\7\20\0\14\7\1\u0138\20\7"+
    "\13\0\1\7\2\0\1\7\20\0\11\7\1\u0139\23\7"+
    "\13\0\1\7\2\0\1\7\20\0\15\7\1\u013a\17\7"+
    "\13\0\1\7\2\0\1\7\20\0\15\7\1\u013b\17\7"+
    "\13\0\1\7\2\0\1\7\20\0\14\7\1\u013c\20\7"+
    "\13\0\1\7\2\0\1\7\20\0\10\7\1\u013d\24\7"+
    "\13\0\1\7\2\0\1\7\32\0\1\u013e\61\0\12\7"+
    "\1\u013f\22\7\13\0\1\7\2\0\1\7\20\0\7\7"+
    "\1\u0140\25\7\13\0\1\7\2\0\1\7\20\0\23\7"+
    "\1\u0141\11\7\13\0\1\7\2\0\1\7\20\0\14\7"+
    "\1\u0142\20\7\13\0\1\7\2\0\1\7\20\0\7\7"+
    "\1\u0143\25\7\13\0\1\7\2\0\1\7\20\0\31\7"+
    "\1\u0144\3\7\13\0\1\7\2\0\1\7\45\0\1\u0145"+
    "\46\0\25\7\1\u0146\7\7\13\0\1\7\2\0\1\7"+
    "\20\0\12\7\1\u0147\22\7\13\0\1\7\2\0\1\7"+
    "\20\0\20\7\1\u0148\14\7\13\0\1\7\2\0\1\7"+
    "\20\0\6\7\1\u0149\26\7\13\0\1\7\2\0\1\7"+
    "\27\0\1\u014a\64\0\7\7\1\u014b\25\7\13\0\1\7"+
    "\2\0\1\7\20\0\10\7\1\u014c\24\7\13\0\1\7"+
    "\2\0\1\7\12\0\1\u014d\2\0\54\u014d\3\0\13\u014d"+
    "\2\0\3\u014d\35\u014e\13\u014d\1\u014e\2\0\1\7\12\u014d"+
    "\30\0\1\u014f\51\0\22\7\1\u0150\12\7\13\0\1\7"+
    "\2\0\1\7\30\0\1\u0151\63\0\10\7\1\u0152\24\7"+
    "\13\0\1\7\2\0\1\7\37\0\1\u0153\54\0\17\7"+
    "\1\u0154\15\7\13\0\1\7\2\0\1\7\35\0\1\u0155"+
    "\56\0\15\7\1\u0156\17\7\13\0\1\7\2\0\1\7"+
    "\27\0\1\u0157\64\0\7\7\1\u0158\25\7\13\0\1\7"+
    "\2\0\1\7\33\0\1\u0159\60\0\13\7\1\u015a\21\7"+
    "\13\0\1\7\2\0\1\7\35\0\1\u015b\56\0\15\7"+
    "\1\u015c\17\7\13\0\1\7\2\0\1\7\74\0\1\u015d"+
    "\17\0\35\7\13\0\1\7\2\0\1\7\1\u015d\74\0"+
    "\1\u015e\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[15600];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\1\1\11\3\1\1\11\24\1\13\11\10\1"+
    "\2\0\1\1\1\11\2\1\1\0\2\11\55\1\16\11"+
    "\1\1\1\11\2\0\65\1\1\0\205\1\1\0\12\1"+
    "\1\0\6\1\1\0\4\1\1\0\2\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[350];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
        StringBuffer string = new StringBuffer();

        private Symbol symbol(int type) {
         return new Symbol(type, yyline, yycolumn);
        }
        private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
        }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  TypeScriptLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2868) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println(" "+yytext());
            }
          case 106: break;
          case 2: 
            { System.out.println("DIVISION "+yytext()); return symbol(sym.DIVISION);
            }
          case 107: break;
          case 3: 
            { System.out.println("POR "+yytext()); return symbol(sym.POR);
            }
          case 108: break;
          case 4: 
            { System.out.println("Identifier "+yytext()); return symbol(sym.IDENTIFIER);
            }
          case 109: break;
          case 5: 
            { System.out.println("DecIntegerLiteral "+yytext()); return symbol(sym.INTEGER_LITERAL);
            }
          case 110: break;
          case 6: 
            { System.out.println("PARENTHESIS_OPEN "+yytext()); return symbol(sym.PARENTHESIS_OPEN);
            }
          case 111: break;
          case 7: 
            { System.out.println("PARENTHESIS_CLOSE "+yytext()); return symbol(sym.PARENTHESIS_CLOSE);
            }
          case 112: break;
          case 8: 
            { System.out.println("puntoYcoma "+yytext()); return symbol(sym.puntoYcoma);
            }
          case 113: break;
          case 9: 
            { System.out.println("punto "+yytext()); return symbol(sym.punto);
            }
          case 114: break;
          case 10: 
            { System.out.println("Dospunto "+yytext()); return symbol(sym.punto);
            }
          case 115: break;
          case 11: 
            { System.out.println("corchete_open"+yytext()); return symbol(sym.corchete_open);
            }
          case 116: break;
          case 12: 
            { System.out.println("corchete_close "+yytext()); return symbol(sym.corchete_close);
            }
          case 117: break;
          case 13: 
            { System.out.println("llave_open"+yytext()); return symbol(sym.llave_open);
            }
          case 118: break;
          case 14: 
            { System.out.println("llave_close "+yytext()); return symbol(sym.llave_close);
            }
          case 119: break;
          case 15: 
            { System.out.println("coma "+yytext()); return symbol(sym.coma);
            }
          case 120: break;
          case 16: 
            { string.setLength(0); yybegin(STRING);
            }
          case 121: break;
          case 17: 
            { System.out.println("PLUS "+yytext()); return symbol(sym.PLUS);
            }
          case 122: break;
          case 18: 
            { System.out.println("EQ "+yytext()); return symbol(sym.EQ);
            }
          case 123: break;
          case 19: 
            { System.out.println("Menos "+yytext()); return symbol(sym.Menos);
            }
          case 124: break;
          case 20: 
            { System.out.println("PORCENTAJE "+yytext()); return symbol(sym.PORCENTAJE);
            }
          case 125: break;
          case 21: 
            { System.out.println("NOT "+yytext()); return symbol(sym.NOT);
            }
          case 126: break;
          case 22: 
            { System.out.println("MAYORQUE "+yytext()); return symbol(sym.MAYORQUE);
            }
          case 127: break;
          case 23: 
            { System.out.println("MENORQUE "+yytext()); return symbol(sym.MENORQUE);
            }
          case 128: break;
          case 24: 
            { string.append( yytext() );
            }
          case 129: break;
          case 25: 
            { yybegin(YYINITIAL); 
                                       return symbol(sym.STRING_LITERAL, 
                                       string.toString());
            }
          case 130: break;
          case 26: 
            { string.append('\\');
            }
          case 131: break;
          case 27: 
            { System.out.println("Comment"+yytext());
            }
          case 132: break;
          case 28: 
            { System.out.println("DIVISIONIGUAL "+yytext()); return symbol(sym.DIVISIONIGUAL);
            }
          case 133: break;
          case 29: 
            { System.out.println("PORIGUAL "+yytext()); return symbol(sym.PORIGUAL);
            }
          case 134: break;
          case 30: 
            { System.out.println("AS "+yytext()); return symbol(sym.AS);
            }
          case 135: break;
          case 31: 
            { System.out.println("OF "+yytext()); return symbol(sym.OF);
            }
          case 136: break;
          case 32: 
            { System.out.println("IN "+yytext()); return symbol(sym.IN);
            }
          case 137: break;
          case 33: 
            { System.out.println("IF "+yytext()); return symbol(sym.IF);
            }
          case 138: break;
          case 34: 
            { System.out.println("DO "+yytext()); return symbol(sym.DO);
            }
          case 139: break;
          case 35: 
            { System.out.println("INCREMENTO "+yytext()); return symbol(sym.INCREMENTO);
            }
          case 140: break;
          case 36: 
            { System.out.println("EQEQ "+yytext()); return symbol(sym.EQEQ);
            }
          case 141: break;
          case 37: 
            { System.out.println("MENOSIGUAL "+yytext()); return symbol(sym.MENOSIGUAL);
            }
          case 142: break;
          case 38: 
            { System.out.println("DECREMENTO "+yytext()); return symbol(sym.DECREMENTO);
            }
          case 143: break;
          case 39: 
            { System.out.println("PorcentajeIGUAL "+yytext()); return symbol(sym.PorcentajeIGUAL);
            }
          case 144: break;
          case 40: 
            { System.out.println("COMPARAIUAL "+yytext()); return symbol(sym.COMPARAIUAL);
            }
          case 145: break;
          case 41: 
            { System.out.println("MENORIGUAL "+yytext()); return symbol(sym.MENORIGUAL);
            }
          case 146: break;
          case 42: 
            { System.out.println("MAYORIGUAL "+yytext()); return symbol(sym.MAYORIGUAL);
            }
          case 147: break;
          case 43: 
            { System.out.println("AND "+yytext()); return symbol(sym.AND);
            }
          case 148: break;
          case 44: 
            { System.out.println("OR "+yytext()); return symbol(sym.OR);
            }
          case 149: break;
          case 45: 
            { string.append('\t');
            }
          case 150: break;
          case 46: 
            { string.append('\r');
            }
          case 151: break;
          case 47: 
            { string.append('\n');
            }
          case 152: break;
          case 48: 
            { string.append('\"');
            }
          case 153: break;
          case 49: 
            { System.out.println("ANY "+yytext()); return symbol(sym.ANY);
            }
          case 154: break;
          case 50: 
            { System.out.println("SET "+yytext()); return symbol(sym.SET);
            }
          case 155: break;
          case 51: 
            { System.out.println("TRY "+yytext()); return symbol(sym.TRY);
            }
          case 156: break;
          case 52: 
            { System.out.println("LET "+yytext()); return symbol(sym.LET);
            }
          case 157: break;
          case 53: 
            { System.out.println("NEW "+yytext()); return symbol(sym.NEW);
            }
          case 158: break;
          case 54: 
            { System.out.println("FOR "+yytext()); return symbol(sym.FOR);
            }
          case 159: break;
          case 55: 
            { System.out.println("VAR "+yytext()); return symbol(sym.VAR);
            }
          case 160: break;
          case 56: 
            { System.out.println("GET "+yytext()); return symbol(sym.GET);
            }
          case 161: break;
          case 57: 
            { System.out.println("TRUE "+yytext()); return symbol(sym.TRUE);
            }
          case 162: break;
          case 58: 
            { System.out.println("THIS "+yytext()); return symbol(sym.THIS);
            }
          case 163: break;
          case 59: 
            { System.out.println("TYPE "+yytext()); return symbol(sym.TYPE);
            }
          case 164: break;
          case 60: 
            { System.out.println("CASE "+yytext()); return symbol(sym.CASE);
            }
          case 165: break;
          case 61: 
            { System.out.println("ELSE "+yytext()); return symbol(sym.ELSE);
            }
          case 166: break;
          case 62: 
            { System.out.println("ENUM "+yytext()); return symbol(sym.ENUM);
            }
          case 167: break;
          case 63: 
            { System.out.println("NULL "+yytext()); return symbol(sym.NULL);
            }
          case 168: break;
          case 64: 
            { System.out.println("FROM "+yytext()); return symbol(sym.FROM);
            }
          case 169: break;
          case 65: 
            { System.out.println("WITH "+yytext()); return symbol(sym.WITH);
            }
          case 170: break;
          case 66: 
            { System.out.println("VOID "+yytext()); return symbol(sym.VOID);
            }
          case 171: break;
          case 67: 
            { System.out.println("BREAK "+yytext()); return symbol(sym.BREAK);
            }
          case 172: break;
          case 68: 
            { System.out.println("SUPER "+yytext()); return symbol(sym.SUPER);
            }
          case 173: break;
          case 69: 
            { System.out.println("THROW "+yytext()); return symbol(sym.THROW);
            }
          case 174: break;
          case 70: 
            { System.out.println("CATCH "+yytext()); return symbol(sym.CATCH);
            }
          case 175: break;
          case 71: 
            { System.out.println("CONST "+yytext()); return symbol(sym.CONST);
            }
          case 176: break;
          case 72: 
            { System.out.println("CLASS "+yytext()); return symbol(sym.CLASS);
            }
          case 177: break;
          case 73: 
            { System.out.println("FALSE "+yytext()); return symbol(sym.FALSE);
            }
          case 178: break;
          case 74: 
            { System.out.println("WHILE "+yytext()); return symbol(sym.WHILE);
            }
          case 179: break;
          case 75: 
            { System.out.println("YIELD "+yytext()); return symbol(sym.YIELD);
            }
          case 180: break;
          case 76: 
            { System.out.println("STATIC "+yytext()); return symbol(sym.STATIC);
            }
          case 181: break;
          case 77: 
            { System.out.println("STRING "+yytext()); return symbol(sym.STRING);
            }
          case 182: break;
          case 78: 
            { System.out.println("SWITCH "+yytext()); return symbol(sym.SWITCH);
            }
          case 183: break;
          case 79: 
            { System.out.println("SYMBOL "+yytext()); return symbol(sym.SYMBOL);
            }
          case 184: break;
          case 80: 
            { System.out.println("TYPEOF "+yytext()); return symbol(sym.TYPEOF);
            }
          case 185: break;
          case 81: 
            { System.out.println("RETURN "+yytext()); return symbol(sym.RETURN);
            }
          case 186: break;
          case 82: 
            { System.out.println("EXPORT "+yytext()); return symbol(sym.EXPORT);
            }
          case 187: break;
          case 83: 
            { System.out.println("NUMBER "+yytext()); return symbol(sym.NUMBER);
            }
          case 188: break;
          case 84: 
            { System.out.println("IMPORT "+yytext()); return symbol(sym.IMPORT);
            }
          case 189: break;
          case 85: 
            { System.out.println("MODULE "+yytext()); return symbol(sym.MODULE);
            }
          case 190: break;
          case 86: 
            { System.out.println("PUBLIC "+yytext()); return symbol(sym.PUBLIC);
            }
          case 191: break;
          case 87: 
            { System.out.println("DELETE "+yytext()); return symbol(sym.DELETE);
            }
          case 192: break;
          case 88: 
            { System.out.println("BOOLEAN "+yytext()); return symbol(sym.BOOLEAN);
            }
          case 193: break;
          case 89: 
            { System.out.println("REQUIRE "+yytext()); return symbol(sym.REQUIRE);
            }
          case 194: break;
          case 90: 
            { System.out.println("EXTENDS "+yytext()); return symbol(sym.EXTENDS);
            }
          case 195: break;
          case 91: 
            { System.out.println("FINALLY "+yytext()); return symbol(sym.FINALLY);
            }
          case 196: break;
          case 92: 
            { System.out.println("PACKAGE "+yytext()); return symbol(sym.PACKAGE);
            }
          case 197: break;
          case 93: 
            { System.out.println("PRIVATE "+yytext()); return symbol(sym.PRIVATE);
            }
          case 198: break;
          case 94: 
            { System.out.println("DECLARE "+yytext()); return symbol(sym.DECLARE);
            }
          case 199: break;
          case 95: 
            { System.out.println("DEFAULT "+yytext()); return symbol(sym.DEFAULT);
            }
          case 200: break;
          case 96: 
            { System.out.println("ABSTRACT "+yytext()); return symbol(sym.ABSTRACT);
            }
          case 201: break;
          case 97: 
            { System.out.println("CONTINUE "+yytext()); return symbol(sym.CONTINUE);
            }
          case 202: break;
          case 98: 
            { System.out.println("FUCTION "+yytext()); return symbol(sym.FUNCTION);
            }
          case 203: break;
          case 99: 
            { System.out.println("DEBURGGER "+yytext()); return symbol(sym.DEBUGGER);
            }
          case 204: break;
          case 100: 
            { System.out.println("INTERFACE "+yytext()); return symbol(sym.INTERFACE);
            }
          case 205: break;
          case 101: 
            { System.out.println("PROTECTED "+yytext()); return symbol(sym.PROTECTED);
            }
          case 206: break;
          case 102: 
            { System.out.println("INSTANCEOF "+yytext()); return symbol(sym.INSTANCEOF);
            }
          case 207: break;
          case 103: 
            { System.out.println("IMPLEMENTS "+yytext()); return symbol(sym.IMPLEMENTS);
            }
          case 208: break;
          case 104: 
            { System.out.println("CONSTRUCTOR "+yytext()); return symbol(sym.CONSTRUCTOR);
            }
          case 209: break;
          case 105: 
            { System.out.println("MASIGUAL "+yytext()); return symbol(sym.MASIGUAL);
            }
          case 210: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
